name: Enviar Mensagem Romantica

on:
  schedule:
    - cron: '0 10 * * *'  # Dispara às 07:00 da manhã no horário do Brasil (GMT-3)
    - cron: '0 19 * * *'  # Dispara às 16:00 da tarde no horário do Brasil (GMT-3)
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Push OneSignal
        run: |
          curl --request POST \
            --url 'https://onesignal.com/api/v1/notifications' \
            --header 'accept: application/json' \
            --header 'authorization: Basic SEU_REST_API_KEY_AQUI' \
            --header 'content-type: application/json' \
            --data '{"app_id": "8de67aa1-123f-438c-b6ce-85c1d48ce75d", "included_segments": ["All"], "contents": {"en": "Bom dia, meu amor! Você é a razão do meu sorriso todos os dias. ❤️", "pt": "Bom dia, meu amor! Você é a razão do meu sorriso todos os dias. ❤️"}, "headings": {"en": "Nosso Diário", "pt": "Nosso Diário"}}'
            
